version: "3.8"

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./api/Dockerfile
    command: npm run start:dev
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nesjs-network
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
      - mongo-express
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./api/Dockerfile
    command: npm run start:prod
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
      - 9229:9229
    expose:
      - 3000
    networks:
      - nesjs-network
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    #   - MONGO_INITDB_DATABASE=test
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - nesjs-network
    ports:
      - 8081:8081
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:3
    networks:
      - nesjs-network
networks:
  nesjs-network:
